### PR TITLE
Add langtools

### PR DESCRIPTION
**Pull request by rgoessl**

### CODE REVIEW

**Comment by mpharoah-d2l** [comment]
What are the changes in the language fixes? Is it just POSIX newline to Windows newline?

**Comment by mpharoah-d2l** [comment]
You can remove `serge/copy-to-lang.sh` now since it does the same thing but using a shells script

**Comment by mpharoah-d2l** [comment]
And update `travis-verify-lang.sh` to change the error message to say to run langtools instead of running `copy-to-lang,sh`

**Comment by mpharoah-d2l** [comment]
Actually, we could just add `lang` to `.gitignore` and have Travis automatically copy the langterms over. I'm not sure why I wasn't doing that before

**Comment by rgoessl** [comment]
> 
> 
> What are the changes in the language files? Is it just POSIX newline to Windows newline?

Missing terms got added in. Tabbing was changed to be consistent across all files (4 spaces)

**Pull request merged**
